default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
#  username: clinic_admin
#  password: clinic
  pool: 5

development:
  <<: *default
  database: clinic_development

production:
  <<: *default
  database: clinic_production

test:
  <<: *default
  database: clinic_test
