# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96abd095d50e1126a0c63a56142025578ecd0913ec9a845359a4006f0d788464ad28316e3beeda1436745abcbf05fbb6602b0dfe0c33e0bb3b466036e75c3427

test:
  secret_key_base: c02aefe52408c205a6c1bdeffcff0037fa24ef7853fdf7bf0e9ef9363a1f8577eb7f7b667726e518046adf28500832e5f5eb4c2e728314e1564bab52d4390204

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
